general:
  host: "0.0.0.0"
  port: 8080
  use_gzip: true
  allowed_origins: ["http://localhost:5173"]

cache:
  # Docker: use "valkey" as the host - it resolves inside the Docker network.
  dsn: "redis://valkey:6379/0"

  # Local Valkey or Redis-compatible server
  # dsn: "redis://localhost:6379/0"

  # Disable cache/rate-limit backing store
  # dsn: ""

database:
  # Docker (make up): use "db" as the host - it resolves inside the Docker network.
  dsn: "postgres://echo:echo@db:5432/echo?sslmode=disable"
  
  # Local requires the superuser
  # `go run .` / `go build` and run `./Echo`
  # dsn: "postgres://postgres:postgres@localhost:5432/echo?sslmode=disable"

  # In Memory mode (No DB and loses all pastes on restart)
  # dsn: ""

pastes:
  max_files: 5
  max_file_size: 350000
  id_length: 8
  token_length: 32

ratelimits:
  - route:         # Route path e.g. /pastes
    method: "GET"  # HTTP Method. e.g. GET (Defaults to GET) if not passed.
    rate: 10       # X per Y seconds
    per: 60        # as seconds
